# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/temp/JAA/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/temp/JAA/source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/temp/JAA/source/CMakeFiles /mnt/temp/JAA/source/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/temp/JAA/source/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JAA

# Build rule for target.
JAA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA
.PHONY : JAA

# fast build rule for target.
JAA/fast:
	$(MAKE) -f CMakeFiles/JAA.dir/build.make CMakeFiles/JAA.dir/build
.PHONY : JAA/fast

#=============================================================================
# Target rules for targets named JAA_ct

# Build rule for target.
JAA_ct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_ct
.PHONY : JAA_ct

# fast build rule for target.
JAA_ct/fast:
	$(MAKE) -f GUI/CompressorThread/CMakeFiles/JAA_ct.dir/build.make GUI/CompressorThread/CMakeFiles/JAA_ct.dir/build
.PHONY : JAA_ct/fast

#=============================================================================
# Target rules for targets named JAA_dus

# Build rule for target.
JAA_dus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_dus
.PHONY : JAA_dus

# fast build rule for target.
JAA_dus/fast:
	$(MAKE) -f GUI/DataUnitsToQString/CMakeFiles/JAA_dus.dir/build.make GUI/DataUnitsToQString/CMakeFiles/JAA_dus.dir/build
.PHONY : JAA_dus/fast

#=============================================================================
# Target rules for targets named JAA_face

# Build rule for target.
JAA_face: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_face
.PHONY : JAA_face

# fast build rule for target.
JAA_face/fast:
	$(MAKE) -f GUI/Face/CMakeFiles/JAA_face.dir/build.make GUI/Face/CMakeFiles/JAA_face.dir/build
.PHONY : JAA_face/fast

#=============================================================================
# Target rules for targets named JAA_filelist

# Build rule for target.
JAA_filelist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_filelist
.PHONY : JAA_filelist

# fast build rule for target.
JAA_filelist/fast:
	$(MAKE) -f GUI/FileList/CMakeFiles/JAA_filelist.dir/build.make GUI/FileList/CMakeFiles/JAA_filelist.dir/build
.PHONY : JAA_filelist/fast

#=============================================================================
# Target rules for targets named JAA_settings_panel

# Build rule for target.
JAA_settings_panel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_settings_panel
.PHONY : JAA_settings_panel

# fast build rule for target.
JAA_settings_panel/fast:
	$(MAKE) -f GUI/SettingsPanels/CMakeFiles/JAA_settings_panel.dir/build.make GUI/SettingsPanels/CMakeFiles/JAA_settings_panel.dir/build
.PHONY : JAA_settings_panel/fast

#=============================================================================
# Target rules for targets named JAA_stw

# Build rule for target.
JAA_stw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_stw
.PHONY : JAA_stw

# fast build rule for target.
JAA_stw/fast:
	$(MAKE) -f GUI/StatInfoW/CMakeFiles/JAA_stw.dir/build.make GUI/StatInfoW/CMakeFiles/JAA_stw.dir/build
.PHONY : JAA_stw/fast

#=============================================================================
# Target rules for targets named JAA_compressor

# Build rule for target.
JAA_compressor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_compressor
.PHONY : JAA_compressor

# fast build rule for target.
JAA_compressor/fast:
	$(MAKE) -f Compressor/CMakeFiles/JAA_compressor.dir/build.make Compressor/CMakeFiles/JAA_compressor.dir/build
.PHONY : JAA_compressor/fast

#=============================================================================
# Target rules for targets named JAA_codec

# Build rule for target.
JAA_codec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_codec
.PHONY : JAA_codec

# fast build rule for target.
JAA_codec/fast:
	$(MAKE) -f Compressor/Codec/CMakeFiles/JAA_codec.dir/build.make Compressor/Codec/CMakeFiles/JAA_codec.dir/build
.PHONY : JAA_codec/fast

#=============================================================================
# Target rules for targets named JAA_codec_bwt

# Build rule for target.
JAA_codec_bwt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_codec_bwt
.PHONY : JAA_codec_bwt

# fast build rule for target.
JAA_codec_bwt/fast:
	$(MAKE) -f Compressor/Codec/Codecs/BWT/CMakeFiles/JAA_codec_bwt.dir/build.make Compressor/Codec/Codecs/BWT/CMakeFiles/JAA_codec_bwt.dir/build
.PHONY : JAA_codec_bwt/fast

#=============================================================================
# Target rules for targets named JAA_divsuf

# Build rule for target.
JAA_divsuf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_divsuf
.PHONY : JAA_divsuf

# fast build rule for target.
JAA_divsuf/fast:
	$(MAKE) -f Compressor/Codec/Codecs/BWT/divsuf/CMakeFiles/JAA_divsuf.dir/build.make Compressor/Codec/Codecs/BWT/divsuf/CMakeFiles/JAA_divsuf.dir/build
.PHONY : JAA_divsuf/fast

#=============================================================================
# Target rules for targets named JAA_codec_huff

# Build rule for target.
JAA_codec_huff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_codec_huff
.PHONY : JAA_codec_huff

# fast build rule for target.
JAA_codec_huff/fast:
	$(MAKE) -f Compressor/Codec/Codecs/HUFF/CMakeFiles/JAA_codec_huff.dir/build.make Compressor/Codec/Codecs/HUFF/CMakeFiles/JAA_codec_huff.dir/build
.PHONY : JAA_codec_huff/fast

#=============================================================================
# Target rules for targets named JAA_codec_mtf

# Build rule for target.
JAA_codec_mtf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_codec_mtf
.PHONY : JAA_codec_mtf

# fast build rule for target.
JAA_codec_mtf/fast:
	$(MAKE) -f Compressor/Codec/Codecs/MTF/CMakeFiles/JAA_codec_mtf.dir/build.make Compressor/Codec/Codecs/MTF/CMakeFiles/JAA_codec_mtf.dir/build
.PHONY : JAA_codec_mtf/fast

#=============================================================================
# Target rules for targets named JAA_codec_rle

# Build rule for target.
JAA_codec_rle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_codec_rle
.PHONY : JAA_codec_rle

# fast build rule for target.
JAA_codec_rle/fast:
	$(MAKE) -f Compressor/Codec/Codecs/RLE/CMakeFiles/JAA_codec_rle.dir/build.make Compressor/Codec/Codecs/RLE/CMakeFiles/JAA_codec_rle.dir/build
.PHONY : JAA_codec_rle/fast

#=============================================================================
# Target rules for targets named JAA_datablock

# Build rule for target.
JAA_datablock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_datablock
.PHONY : JAA_datablock

# fast build rule for target.
JAA_datablock/fast:
	$(MAKE) -f Compressor/DataBlock/CMakeFiles/JAA_datablock.dir/build.make Compressor/DataBlock/CMakeFiles/JAA_datablock.dir/build
.PHONY : JAA_datablock/fast

#=============================================================================
# Target rules for targets named JAA_filestable

# Build rule for target.
JAA_filestable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_filestable
.PHONY : JAA_filestable

# fast build rule for target.
JAA_filestable/fast:
	$(MAKE) -f Compressor/FilesTable/CMakeFiles/JAA_filestable.dir/build.make Compressor/FilesTable/CMakeFiles/JAA_filestable.dir/build
.PHONY : JAA_filestable/fast

#=============================================================================
# Target rules for targets named JAA_crc

# Build rule for target.
JAA_crc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 JAA_crc
.PHONY : JAA_crc

# fast build rule for target.
JAA_crc/fast:
	$(MAKE) -f Compressor/CRC/CMakeFiles/JAA_crc.dir/build.make Compressor/CRC/CMakeFiles/JAA_crc.dir/build
.PHONY : JAA_crc/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/JAA.dir/build.make CMakeFiles/JAA.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/JAA.dir/build.make CMakeFiles/JAA.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/JAA.dir/build.make CMakeFiles/JAA.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... JAA"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... JAA_ct"
	@echo "... JAA_dus"
	@echo "... JAA_face"
	@echo "... JAA_filelist"
	@echo "... JAA_settings_panel"
	@echo "... JAA_stw"
	@echo "... JAA_compressor"
	@echo "... JAA_codec"
	@echo "... JAA_codec_bwt"
	@echo "... JAA_divsuf"
	@echo "... JAA_codec_huff"
	@echo "... JAA_codec_mtf"
	@echo "... JAA_codec_rle"
	@echo "... JAA_datablock"
	@echo "... JAA_filestable"
	@echo "... JAA_crc"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

